get:
  operationId: get-environments
  tags: [ Environments ]
  summary: Get all environments.
  description: |
    This method allows to retrieve all environments stored in selected project.
  parameters:
    - $ref: '../parameters/project/Code.yaml'
    - $ref: '../parameters/pagination/Limit.yaml'
    - $ref: '../parameters/pagination/Offset.yaml'
  responses:
    200:
      description: A list of all environments.
      content:
        application/json:
          schema:
            $ref: '../schemas/responses/EnvironmentList.yaml'

post:
  operationId: create-environment
  tags: [ Environments ]
  summary: Create a new environment.
  description: |
    This method allows to create an environment in selected project.
  parameters:
    - $ref: '../parameters/project/Code.yaml'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/Environment.create.yaml'
  responses:
    200:
      description: A result.
      content:
        application/json:
          schema:
            $ref: '../schemas/responses/Id.yaml'
