get:
  operationId: get-environments
  tags: [ environments ]
  summary: Get all environments.
  description: |
    This method allows to retrieve all environments stored in selected project.
  parameters:
    - $ref: '../parameters/Code.yaml'
    - $ref: '../parameters/pagination/Limit.yaml'
    - $ref: '../parameters/pagination/Offset.yaml'
  responses:
    200:
      description: A list of all environments.
      content:
        application/json:
          schema:
            $ref: '../schemas/responses/EnvironmentList.yaml'
    400:
      description: Bad Request.
    401:
      description: Unauthorized.
    403:
      description: Forbidden.
    404:
      description: Not Found.
    429:
      description: Too Many Requests.

post:
  operationId: create-environment
  tags: [ environments ]
  summary: Create a new environment.
  description: |
    This method allows to create an environment in selected project.
  parameters:
    - $ref: '../parameters/Code.yaml'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/Environment.create.yaml'
  responses:
    200:
      description: A result.
      content:
        application/json:
          schema:
            $ref: '../schemas/responses/Id.yaml'
    400:
      description: Bad Request.
    401:
      description: Unauthorized.
    403:
      description: Forbidden.
    404:
      description: Not Found.
    422:
      description: Unprocessable Entity.
    429:
      description: Too Many Requests.
