get:
  operationId: get-environment
  tags: [ environments ]
  summary: Get a specific environment.
  description: |
    This method allows to retrieve a specific environment.
  parameters:
    - $ref: '../parameters/Code.yaml'
    - $ref: '../parameters/Id.yaml'
  responses:
    200:
      description: An environment.
      content:
        application/json:
          schema:
            $ref: '../schemas/responses/Environment.yaml'
    400:
      description: Bad Request.
    401:
      description: Unauthorized.
    403:
      description: Forbidden.
    404:
      description: Not Found.
    429:
      description: Too Many Requests.

delete:
  operationId: delete-environment
  tags: [ environments ]
  summary: Delete environment.
  description: |
    This method completely deletes an environment from repository.
  parameters:
    - $ref: '../parameters/Code.yaml'
    - $ref: '../parameters/Id.yaml'
  responses:
    200:
      description: A Result.
      content:
        application/json:
          schema:
            $ref: '../schemas/responses/Id.yaml'
    400:
      description: Bad Request.
    401:
      description: Unauthorized.
    403:
      description: Forbidden.
    404:
      description: Not Found.
    429:
      description: Too Many Requests.

patch:
  operationId: update-environment
  tags: [ environments ]
  summary: Update environment.
  description: |
    This method updates an environment.
  parameters:
    - $ref: '../parameters/Code.yaml'
    - $ref: '../parameters/Id.yaml'
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: '../schemas/Environment.update.yaml'
  responses:
    200:
      description: A result.
      content:
        application/json:
          schema:
            $ref: '../schemas/responses/Id.yaml'
    400:
      description: Bad Request.
    401:
      description: Unauthorized.
    403:
      description: Forbidden.
    404:
      description: Not Found.
    429:
      description: Too Many Requests.
